#!/usr/bin/env bash
# Generate .env.local wired to the running local Supabase stack.
# Keys come from `supabase status` so they always match the live stack.
# .env.local is gitignored (.env*.local) and never committed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Load KEY="value" pairs from the CLI (API_URL, ANON_KEY, PUBLISHABLE_KEY, SECRET_KEY, ...)
eval "$(supabase status -o env)"

cat > "$REPO_ROOT/.env.local" <<EOF
# Auto-generated by .cursor/gen-env-local.sh — points the app at local Supabase.
# Regenerated on every boot. Gitignored. Not for production.
NEXT_PUBLIC_SITE_URL=http://localhost:3031
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SECRET_KEY=${SECRET_KEY}
EOF

echo "[gen-env-local] Wrote $REPO_ROOT/.env.local (NEXT_PUBLIC_SUPABASE_URL=${API_URL})"
